mobile_path = File.expand_path("../mobile", __dir__)
ENV['NODE_PATH'] = "#{mobile_path}/node_modules"

# Resolve react_native_pods.rb with node pointing to mobile/node_modules
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', mobile_path]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'CarUnlock' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => mobile_path
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
